openapi: 3.0.3
info:
    title: Game Service
    description: Service for a multiplayer game
    version: "1.0"
servers:
    - url: http://localhost:8000
paths:
    /back/items:
        get:
            tags:
                - item
            summary: list item
            description: List all items
            operationId: item#list
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/StoredItemResponseCollection'
                            example:
                                - damage: 40
                                  description: A magnificent sword which grants the bearer +2 wisdom
                                  healing: 36
                                  id: 123abc
                                  name: Sword of Wisdom
                                  protection: 13
                                - damage: 40
                                  description: A magnificent sword which grants the bearer +2 wisdom
                                  healing: 36
                                  id: 123abc
                                  name: Sword of Wisdom
                                  protection: 13
        post:
            tags:
                - item
            summary: add item
            description: Add new item and return its ID
            operationId: item#add
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/AddRequestBody'
                        example:
                            damage: 51
                            description: A magnificent sword which grants the bearer +2 wisdom
                            healing: 54
                            name: Sword of Wisdom
                            protection: 4
            responses:
                "201":
                    description: Created response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Optio sequi voluptatem consequuntur.
                            example: Ratione accusamus quae atque accusantium a aut.
    /back/items/{id}:
        delete:
            tags:
                - item
            summary: remove item
            description: Remove an item
            operationId: item#remove
            parameters:
                - name: id
                  in: path
                  description: ID of item to remove
                  required: true
                  schema:
                    type: string
                    description: ID of item to remove
                    example: Rem numquam nulla ducimus quod.
                  example: Amet praesentium atque quisquam occaecati.
            responses:
                "204":
                    description: No Content response.
                "404":
                    description: 'not_found: Item not found'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/NotFound'
                            example:
                                id: Alias velit veritatis et.
                                message: Dolorem veritatis et ipsum.
        get:
            tags:
                - item
            summary: show item
            description: Show item by ID
            operationId: item#show
            parameters:
                - name: view
                  in: query
                  description: View to render
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: View to render
                    example: default
                    enum:
                        - default
                        - tiny
                  example: tiny
                - name: id
                  in: path
                  description: ID of item to show
                  required: true
                  schema:
                    type: string
                    description: ID of item to show
                    example: Perferendis corrupti eos.
                  example: Quibusdam ullam et doloremque laboriosam totam ea.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/StoredItem'
                            example:
                                damage: 59
                                description: A magnificent sword which grants the bearer +2 wisdom
                                healing: 40
                                id: 123abc
                                name: Sword of Wisdom
                                protection: 19
                "404":
                    description: 'not_found: Item not found'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/NotFound'
                            example:
                                id: Ex est omnis qui.
                                message: Quasi qui veniam vel possimus.
        put:
            tags:
                - item
            summary: update item
            description: Update an item with the given ID
            operationId: item#update
            parameters:
                - name: id
                  in: path
                  description: ID of the item to be updated
                  required: true
                  schema:
                    type: string
                    description: ID of the item to be updated
                    example: Fugiat soluta sit molestias ducimus.
                  example: Ipsa nisi eos laboriosam cumque.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UpdateRequestBody'
                        example:
                            item:
                                damage: 154
                                description: A magnificent sword which grants the bearer +2 wisdom
                                healing: 39
                                name: Sword of Wisdom
                                protection: 14
            responses:
                "204":
                    description: No Content response.
                "404":
                    description: 'not_found: Item not found'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/NotFound'
                            example:
                                id: Velit voluptatum.
                                message: Ipsum sequi temporibus harum id.
    /items:
        get:
            tags:
                - front
            summary: list-items front
            description: List all items
            operationId: front#list-items
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/StoredItemCollection'
                            example:
                                - damage: 191
                                  description: A magnificent sword which grants the bearer +2 wisdom
                                  healing: 141
                                  id: 123abc
                                  name: Sword of Wisdom
                                  protection: 9
                                - damage: 191
                                  description: A magnificent sword which grants the bearer +2 wisdom
                                  healing: 141
                                  id: 123abc
                                  name: Sword of Wisdom
                                  protection: 9
components:
    schemas:
        AddRequestBody:
            type: object
            properties:
                damage:
                    type: integer
                    description: Amount of damage the item can do
                    example: 89
                    minimum: 0
                    maximum: 200
                description:
                    type: string
                    description: Description of item
                    example: A magnificent sword which grants the bearer +2 wisdom
                    maxLength: 2000
                healing:
                    type: integer
                    description: Amount of healing the item can provide
                    example: 17
                    minimum: 0
                    maximum: 200
                name:
                    type: string
                    description: Name of item
                    example: Sword of Wisdom
                    maxLength: 100
                protection:
                    type: integer
                    description: Amount of protection the item can provide
                    example: 11
                    minimum: 0
                    maximum: 20
            example:
                damage: 84
                description: A magnificent sword which grants the bearer +2 wisdom
                healing: 91
                name: Sword of Wisdom
                protection: 15
            required:
                - name
                - damage
                - healing
                - protection
        NotFound:
            type: object
            properties:
                id:
                    type: string
                    description: ID of missing item
                    example: Optio mollitia.
                message:
                    type: string
                    description: not found
                    example: Voluptas et non.
            description: Item not found
            example:
                id: Et aut odit.
                message: Harum autem ipsam ratione atque voluptatibus.
            required:
                - message
                - id
        StoredItem:
            type: object
            properties:
                damage:
                    type: integer
                    description: Amount of damage the item can do
                    example: 65
                    minimum: 0
                    maximum: 200
                description:
                    type: string
                    description: Description of item
                    example: A magnificent sword which grants the bearer +2 wisdom
                    maxLength: 2000
                healing:
                    type: integer
                    description: Amount of healing the item can provide
                    example: 75
                    minimum: 0
                    maximum: 200
                id:
                    type: string
                    description: ID is the unique id of the item.
                    example: 123abc
                name:
                    type: string
                    description: Name of item
                    example: Sword of Wisdom
                    maxLength: 100
                protection:
                    type: integer
                    description: Amount of protection the item can provide
                    example: 15
                    minimum: 0
                    maximum: 20
            example:
                damage: 26
                description: A magnificent sword which grants the bearer +2 wisdom
                healing: 87
                id: 123abc
                name: Sword of Wisdom
                protection: 19
            required:
                - id
                - name
                - damage
                - healing
                - protection
        StoredItemCollection:
            type: array
            items:
                $ref: '#/components/schemas/StoredItem'
            example:
                - damage: 191
                  description: A magnificent sword which grants the bearer +2 wisdom
                  healing: 141
                  id: 123abc
                  name: Sword of Wisdom
                  protection: 9
                - damage: 191
                  description: A magnificent sword which grants the bearer +2 wisdom
                  healing: 141
                  id: 123abc
                  name: Sword of Wisdom
                  protection: 9
                - damage: 191
                  description: A magnificent sword which grants the bearer +2 wisdom
                  healing: 141
                  id: 123abc
                  name: Sword of Wisdom
                  protection: 9
                - damage: 191
                  description: A magnificent sword which grants the bearer +2 wisdom
                  healing: 141
                  id: 123abc
                  name: Sword of Wisdom
                  protection: 9
        StoredItemResponse:
            type: object
            properties:
                damage:
                    type: integer
                    description: Amount of damage the item can do
                    example: 156
                    minimum: 0
                    maximum: 200
                description:
                    type: string
                    description: Description of item
                    example: A magnificent sword which grants the bearer +2 wisdom
                    maxLength: 2000
                healing:
                    type: integer
                    description: Amount of healing the item can provide
                    example: 162
                    minimum: 0
                    maximum: 200
                id:
                    type: string
                    description: ID is the unique id of the item.
                    example: 123abc
                name:
                    type: string
                    description: Name of item
                    example: Sword of Wisdom
                    maxLength: 100
                protection:
                    type: integer
                    description: Amount of protection the item can provide
                    example: 8
                    minimum: 0
                    maximum: 20
            description: A StoredItem describes an item stored with an ID (default view)
            example:
                damage: 23
                description: A magnificent sword which grants the bearer +2 wisdom
                healing: 172
                id: 123abc
                name: Sword of Wisdom
                protection: 3
            required:
                - id
                - name
                - damage
                - healing
                - protection
        StoredItemResponseCollection:
            type: array
            items:
                $ref: '#/components/schemas/StoredItemResponse'
            description: ListResponseBody is the result type for an array of StoredItemResponse (default view)
            example:
                - damage: 40
                  description: A magnificent sword which grants the bearer +2 wisdom
                  healing: 36
                  id: 123abc
                  name: Sword of Wisdom
                  protection: 13
                - damage: 40
                  description: A magnificent sword which grants the bearer +2 wisdom
                  healing: 36
                  id: 123abc
                  name: Sword of Wisdom
                  protection: 13
        UpdateRequestBody:
            type: object
            properties:
                item:
                    $ref: '#/components/schemas/AddRequestBody'
            example:
                item:
                    damage: 154
                    description: A magnificent sword which grants the bearer +2 wisdom
                    healing: 39
                    name: Sword of Wisdom
                    protection: 14
            required:
                - item
tags:
    - name: item
      description: The item service is the service for managing items
    - name: front
      description: The front service is the main HTTP API for the game
